application: bike-sampa-monitor
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: handler.application

- url: /update
  script: handler.application
  login: admin

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest